# -*- coding: utf-8 -*-
"""pheptinh_tichchap1d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xWxXtNbshXFJZh-_5drm4iOSHoLw-a0
"""

#import library
import numpy as np
import matplotlib.pyplot as plt

#generate signal
N=200
x_signal=np.sin(np.arange(N)/20.)

#Signal add Gaussian noise
x_noise=x_signal+.05*np.random.randn(N)

#visualize signal
plt.figure()
plt.plot(x_signal,label='Signal') #plot signal
plt.plot(x_noise,label='Signal with noise')
plt.title('Signal and Sigal with noise')
plt.legend()

#filter with moving average
w=1./3*np.ones(3) 
x_filter=np.convolve(x_noise,w)

#visualize signal with filter
plt.plot(x_filter) #plot signal
plt.title('Signal and Sigal with noise')